require 'pry'

class Dog

    # attr_reader -> read access, no write
    # attr_writer -> just write access
    # attr_accessor -> read + write access

    # these methods allow a user to see the data
    attr_reader :breed, :number_of_legs

    # these methods allow a user to change the data
    attr_accessor :name, :attitude

    # end goal: to create a dog with 4 attributes / features

    def initialize(name_parameter, breed_parameter, attitude_parameter = "jolly")
        @name = name_parameter
        @breed = breed_parameter
        @number_of_legs = 4
        @attitude = attitude_parameter
        @chip_id = 74365745 #let's assume this is a number generated by some method
    end

    def bark
        puts "woof"
    end

    # GETTER method / reader 
    # def name
    #     @name
    # end

    # def breed
    #     @breed
    # end

    # SETTER method / writer
    # def name=(new_name)
    #     @name = new_name
    # end

    # def breed=(new_breed)
    #     @breed = new_breed
    # end

    # DRY - don't repeat yourself

end

sora = Dog.new("Sora", "lab-pit", "excited")
ruby = Dog.new("Ruby", "malteese")

binding.pry
0